services:
  message-queue:
    image: redis:latest
    container_name: services-queue
    ports:
      - "6003:6379"
  mock-db:
    image: postgres:latest
    container_name: mock-test-services
    environment:
      POSTGRES_DB: mock-test-services
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6001:5432"
